# Generated by Django 6.0.7 on 2026-07-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_primario', models.CharField(default='#1d8797', help_text='Color principal (ej. Diente, botones)', max_length=20)),
                ('color_secundario', models.CharField(default='#0f3856', help_text='Color secundario (ej. Reloj, sidebar, textos)', max_length=20)),
                ('nombre_clinica', models.CharField(default='MediQQTA', help_text='Nombre de la Clínica o Consultorio', max_length=100)),
            ],
        ),
    ]
