# Generated by Django 6.0.7 on 2026-07-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamiento', '0002_configuracionsistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
