# Generated by Django 6.0.7 on 2026-08-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamiento', '0003_paciente_correo_electronico'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo de la clínica para correos y reportes', null=True, upload_to='logos/'),
        ),
    ]
